name: courses_sse_client
description: Ce package implémente un client SSE sur dart:io et dart:html

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1

dev_dependencies:
  test:
  pedantic: ^1.11.0
  restserver:
    git: git@github.com:abasty/restserver.git
  shelf:
  sse:
